name: Init Kubernetes Worker Node

on:
  workflow_run:
    workflows: ["Provision Kubernetes Cluster Infrastructure"]
    types:
      - completed


jobs:
  init-worker:
    runs-on: ubuntu-latest

    env:
      WORKER_NODE_TAG_NAME: natalie-worker-node
      REGION: us-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write private SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Get Worker Node IP from EC2 tag
        id: get-ip
        run: |
          echo "ðŸ” Finding public IP by tag..."
          WORKER_NODE_IP=$(aws ec2 describe-instances \
            --region $REGION \
            --filters "Name=tag:Name,Values=$WORKER_NODE_TAG_NAME" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "âœ… Found IP: $WORKER_NODE_IP"
          echo "WORKER_NODE_IP=$WORKER_NODE_IP" >> $GITHUB_ENV

      - name: Upload and Run Init Worker Script
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa scripts/init_worker_node.sh ubuntu@$WORKER_NODE_IP:/home/ubuntu/init_worker_node.sh
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$WORKER_NODE_IP 'bash /home/ubuntu/init_worker_node.sh'
